server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/hello_db
    username: hello
    password: hello
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: backend-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: WARN